### PR TITLE
Fix Release blank URL + Validation crash

### LINKED ISSUE #107: App releases do not have a valid image ul

### PR DESCRIPTION
**Pull request by creativedrewy**
Fixes #107

### CODE REVIEW

File: packages/core/src/create/release.ts [hunk 1]
```diff
@@ -13,10 +13,10 @@ import { imageSize } from "image-size";
 import type { Keypair, PublicKey } from "@solana/web3.js";
 import type {
   App,
-  Context,
+  Context, MetaplexFileReleaseJsonMetadata,
```
Comment (sdlaver) [inline packages/core/src/create/release.ts:16]: NIT: can we put this on its own line, to match the import style?

File: packages/core/src/create/release.ts [hunk 2]
```diff
@@ -132,6 +120,7 @@ export const createReleaseJson = async (
   };
 
   for (const [locale, strings] of Object.entries(releaseDetails.catalog)) {
+    // @ts-expect-error
```
Comment (sdlaver) [inline packages/core/src/create/release.ts:123]: can you comment what error is being suppressed here and why?

File: packages/core/src/validate/index.ts [hunk 3]
```diff
@@ -2,9 +2,9 @@ import fs from "fs";
 import Ajv from "ajv";
 
 import type {
-  AppMetadata,
+  AppMetadata, MetaplexFileReleaseJsonMetadata,
```
Comment (sdlaver) [inline packages/core/src/validate/index.ts:5]: NIT: can we put this on its own line, to match the import style?

File: packages/core/src/create/release.ts [hunk 4]
```diff
@@ -104,6 +93,7 @@ export const createReleaseJson = async (
     },
     extensions: {
       solana_dapp_store: {
+        // @ts-expect-error
```
Comment (sdlaver) [inline packages/core/src/create/release.ts:96]: can you comment what error is being suppressed here and why?

File: packages/core/src/types.ts [hunk 5]
```diff
@@ -16,6 +16,16 @@ export type AppMetadata = Omit<AppJsonMetadata, "image"> & {
   image: string | MetaplexFile;
 };
 
+export type MetaplexFileReleaseJsonMetadata = Omit<ReleaseJsonMetadata, "image"> & {
+  image: string | MetaplexFile;
```
Comment (sdlaver) [inline packages/core/src/types.ts:20]: If `media` and `files` can be strictly `MetaplexFile` objects, can we do the same for `image`, to make the modifications to the generated type consistent?

Also, why is `Omit` needed for `image`, but not for `extensions.solana_dapp_store.[media|files]`?

File: packages/core/src/create/release.ts (hunk 1 above)
Comment (creativedrewy) [reply packages/core/src/create/release.ts:16]: Yes, I think it didn't because I finally turned off auto formatting :)

File: packages/core/src/types.ts (hunk 5 above)
Comment (creativedrewy) [reply packages/core/src/types.ts:20]: I'm wanting to move into a world where our schema files are the source of truth for this stuff; can I use advanced types in schemas?

As for why Omit is used...oddly...I tried, well, omitting using it, and things appeared to work. Might not be needed.

Comment (creativedrewy) [reply packages/core/src/types.ts:20]: Update: I cannot build without `Omit`-ing "image". But for some reason the same run isn't required for `media|files`. Unfortunately right now I don't know why...

File: packages/core/src/create/release.ts (hunk 2 above)
Comment (creativedrewy) [reply packages/core/src/create/release.ts:124]: Interesting, it would appear it has to do with the files & media Metaplex overrides you were wondering about below...

File: packages/core/src/types.ts (hunk 5 above)
Comment (sdlaver) [reply packages/core/src/types.ts:20]: Alright, I can approve as-is, but please file an issue to get this type cleaned up. This has some code smell about it...

**Review by sdlaver — APPROVED** [review]

File: packages/core/src/types.ts (hunk 5 above)
Comment (creativedrewy) [reply packages/core/src/types.ts:20]: Okay yeah this all centers around the tension between what the Metaplex sdk needs and our despire to validate the JSON against the schema.

You're totally right it smells. I'll get it addressed along side some of the other schema cleanup I'm looking into.
